"""Add 2FA columns to users table

Revision ID: 3fa9c5b8d1e2
Revises: 8ea0e6e78604
Create Date: 2026-03-14 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa9c5b8d1e2'
down_revision = '8ea0e6e78604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twofa_secret', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('twofa_enabled', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twofa_enabled')
    op.drop_column('users', 'twofa_secret')
    # ### end Alembic commands ###
